# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c043fc9eaf14aa66e8bcf780da57c5b269cf74175675d98e48e02ef2f1ad728f2b5b41461c85a1cf3376ab3935662690dd06f910696fab42058fb8557a57a808

test:
  secret_key_base: f98cda4c1ec16eca64561d48f78e1f0b2e9365b68c3303efd1202fe143b1a9ee08e32c3169eb1c1242e3f87cd58ac7cfec96feb6e9d2f98ce232d64c8b5bd2fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
